### ISSUE TITLE
Control over `pdxinfo` contents

### ISSUE THREAD

**Issue by adamsoutar** [pd-rs/crank#21]
Hey,

Absolutely love these tools! Just wondering, when packaging up for a nice, proper app on the Playdate home screen, I couldn't seem to find a way to supply `pdxinfo` files?

I'd like to provide a card + launch image for my game, as well as supply the basic info fields like Author etc.

I might just be being silly and have missed for example a specific place I'm meant to put the file in, but I couldn't quite figure it out if that's the case.

Is there a way to do this with crank?

Thanks in advance

**Comment by rtsuk** [comment]
I think I just never implemented that. It might not have existed when I did all the initial work.

**Comment by adamsoutar** [comment]
Gotcha 👍 
I'll have a poke around in the code and PR if I manage to come up with anything useful :)

**Comment by lilyinstarlight** [comment]
I've a branch to do this already actually. Let me check it real quick and PR it so you can take a look at it

**Comment by rtsuk** [comment]
You folks are the best 😄

**Comment by lilyinstarlight** [comment]
See #22
