### ISSUE TITLE
Error on windows about paths 

### ISSUE THREAD

**Issue by boozook** [pd-rs/crank#44]
[This error](https://github.com/pd-rs/crank/actions/runs/5563629855/jobs/10162703673#step:9:235) and [that](https://github.com/pd-rs/crank/actions/runs/5772547705/job/15657957517?pr=45)

<img width="1027" alt="Screenshot 2023-07-15 at 22 29 14" src="https://github.com/pd-rs/crank/assets/888526/48a1a2b4-d51f-4a1f-bf18-2f98b90dba5e">

- - -

Because of [arm-gcc already installed](https://github.com/pd-rs/get-playdate-sdk/pull/14), I'm sure problem in searching-algorithm in crank.

```text
INFO  crank > compile_setup: "C:\\Program Files (x86)\\GNU Tools Arm Embedded\\9 2019-q4-major\\bin\\arm-none-eabi-gcc.exe" "-g3" "-c" "-mthumb" "-mcpu=cortex-m7" "-mfloat-abi=hard" "-mfpu=fpv5-sp-d16" "-D__FPU_USED=1" "-O2" "-falign-functions=16" "-fomit-frame-pointer" "-gdwarf-2" "-Wall" "-Wno-unused" "-Wstrict-prototypes" "-Wno-unknown-pragmas" "-fverbose-asm" "-Wdouble-promotion" "-mword-relocations" "-fno-common" "-ffunction-sections" "-fdata-sections" "-DTARGET_PLAYDATE=1" "-DTARGET_EXTENSION=1" "-fno-exceptions" "C:/Users/runneradmin/Documents/PlaydateSDK\\C_API\\buildsupport\\setup.c" "-I" "C:/Users/runneradmin/Documents/PlaydateSDK\\C_API" "-o" "D:\\a\\crank\\crank\\crankstart\\target\\thumbv7em-none-eabihf\\release\\setup.o"
Error: The system cannot find the path specified. (os error 3)
```

I suppose we need to pass normalized non-windows paths to gcc, replace `\\` with normal separators `/`.

**Comment by parasyte** [comment]
This is fixed by #49
